# Generated by Django 5.2.9 on 2025-12-11 05:25

import mainapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', mainapp.models.UserManager()),
            ],
        ),
    ]
