# Generated by Django 5.2 on 2025-04-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_teacher_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
