# Generated by Django 5.2 on 2025-04-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
