# Generated by Django 5.2 on 2025-04-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_phone_number_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
