# Generated by Django 5.2 on 2025-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_teacher_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
