# Generated by Django 5.2 on 2025-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_teacher_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_assigned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
