# Generated by Django 5.2 on 2025-05-10 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(max_length=100)),
                ('class_assigned', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('attendance', models.FloatField()),
                ('homework', models.FloatField()),
                ('parental_education', models.CharField(max_length=100)),
                ('study_hours', models.FloatField()),
                ('failures', models.IntegerField()),
                ('extracurricular', models.BooleanField()),
                ('participation', models.FloatField()),
                ('rating', models.FloatField()),
                ('discipline', models.FloatField()),
                ('late_submissions', models.IntegerField()),
                ('prev_grade1', models.FloatField()),
                ('prev_grade2', models.FloatField()),
            ],
        ),
    ]
