# Generated by Django 5.2 on 2025-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=10, unique=True)),
                ('total_working_days', models.IntegerField()),
                ('total_homework_given', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
