# Generated by Django 5.2 on 2025-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_class_student_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.CharField(default='Girish Prasad Memorial College', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='school_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
