# Generated by Django 5.2 on 2025-05-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_attendance_remove_student_attendance_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('not_marked', 'Not Marked')], default='not_marked', max_length=10),
        ),
    ]
