# Generated by Django 5.2 on 2025-05-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('class_assigned', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('homework', models.FloatField()),
                ('parental_education', models.CharField(max_length=100)),
                ('study_hours', models.FloatField()),
                ('failures', models.IntegerField()),
                ('extracurricular', models.BooleanField()),
                ('participation', models.FloatField()),
                ('rating', models.FloatField()),
                ('discipline', models.FloatField()),
                ('late_submissions', models.IntegerField()),
                ('prev_grade1', models.FloatField()),
                ('prev_grade2', models.FloatField()),
            ],
        ),
    ]
