# Generated by Django 5.2 on 2025-05-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
