# Generated by Django 5.2 on 2025-05-11 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_student_attendance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
