# Generated by Django 5.2 on 2025-05-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_attendance_date_remove_attendance_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AlterField(
            model_name='student',
            name='discipline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='parental_education',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='participation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_hours',
            field=models.IntegerField(),
        ),
    ]
