# Generated by Django 5.2 on 2025-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_student_gender_alter_student_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='extracurricular',
            field=models.IntegerField(),
        ),
    ]
