# Generated by Django 5.2 on 2025-05-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_student_extracurricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parental_education',
            field=models.IntegerField(),
        ),
    ]
