# Generated by Django 5.2 on 2025-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_student_parental_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='final_grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
