# Generated by Django 5.2 on 2025-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_student_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='threshold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
