# Generated by Django 5.2 on 2025-05-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_class_threshold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
