# Generated by Django 5.2 on 2025-05-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('class_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('students', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Class Attendances',
                'indexes': [models.Index(fields=['school_id', 'class_number', 'date'], name='mainapp_att_school__ecfb00_idx')],
                'unique_together': {('school_id', 'class_number', 'date')},
            },
        ),
    ]
