# Generated by Django 5.2 on 2025-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='total_working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClassWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('class_number', models.CharField(max_length=10)),
                ('working_days', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'class_number'], name='mainapp_cla_school__07a4de_idx')],
                'unique_together': {('school_id', 'class_number')},
            },
        ),
    ]
