# Generated by Django 5.2 on 2025-05-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_class_total_working_days_classworkingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='final_grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
