# Generated by Django 5.2 on 2025-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_student_final_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='final_grade',
            field=models.FloatField(),
        ),
    ]
