# Generated by Django 5.2 on 2025-05-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_student_final_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='total_homework_given',
        ),
        migrations.RemoveField(
            model_name='student',
            name='homework',
        ),
    ]
